//
// Generated by Bluespec Compiler, version 2022.01 (build 066c7a8)
//
// On Wed Jun  8 17:49:51 CEST 2022
//
//
// Ports:
// Name                         I/O  size props
// request_get                    O    35 reg
// RDY_request_get                O     1 reg
// RDY_response_put               O     1 reg
// CLK                            I     1 clock
// RST_N                          I     1 reset
// response_put                   I    16 reg
// EN_response_put                I     1
// EN_request_get                 I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkJ1(CLK,
	    RST_N,

	    EN_request_get,
	    request_get,
	    RDY_request_get,

	    response_put,
	    EN_response_put,
	    RDY_response_put);
  input  CLK;
  input  RST_N;

  // actionvalue method request_get
  input  EN_request_get;
  output [34 : 0] request_get;
  output RDY_request_get;

  // action method response_put
  input  [15 : 0] response_put;
  input  EN_response_put;
  output RDY_response_put;

  // signals for module outputs
  wire [34 : 0] request_get;
  wire RDY_request_get, RDY_response_put;

  // register dsp
  reg [4 : 0] dsp;
  wire [4 : 0] dsp$D_IN;
  wire dsp$EN;

  // register pc
  reg [14 : 0] pc;
  wire [14 : 0] pc$D_IN;
  wire pc$EN;

  // register rsp
  reg [4 : 0] rsp;
  wire [4 : 0] rsp$D_IN;
  wire rsp$EN;

  // register st0
  reg [15 : 0] st0;
  wire [15 : 0] st0$D_IN;
  wire st0$EN;

  // ports of submodule dstack
  wire [15 : 0] dstack$D_IN, dstack$D_OUT_1;
  wire [4 : 0] dstack$ADDR_1,
	       dstack$ADDR_2,
	       dstack$ADDR_3,
	       dstack$ADDR_4,
	       dstack$ADDR_5,
	       dstack$ADDR_IN;
  wire dstack$WE;

  // ports of submodule io_req
  wire [34 : 0] io_req$D_IN, io_req$D_OUT;
  wire io_req$CLR, io_req$DEQ, io_req$EMPTY_N, io_req$ENQ, io_req$FULL_N;

  // ports of submodule io_rsp
  wire [15 : 0] io_rsp$D_IN, io_rsp$D_OUT;
  wire io_rsp$CLR, io_rsp$DEQ, io_rsp$EMPTY_N, io_rsp$ENQ, io_rsp$FULL_N;

  // ports of submodule ram
  wire [15 : 0] ram$DIA, ram$DIB, ram$DOA, ram$DOB;
  wire [13 : 0] ram$ADDRA, ram$ADDRB;
  wire ram$ENA, ram$ENB, ram$WEA, ram$WEB;

  // ports of submodule rstack
  wire [15 : 0] rstack$D_IN, rstack$D_OUT_1;
  wire [4 : 0] rstack$ADDR_1,
	       rstack$ADDR_2,
	       rstack$ADDR_3,
	       rstack$ADDR_4,
	       rstack$ADDR_5,
	       rstack$ADDR_IN;
  wire rstack$WE;

  // rule scheduling signals
  wire CAN_FIRE_RL_run,
       CAN_FIRE_request_get,
       CAN_FIRE_response_put,
       WILL_FIRE_RL_run,
       WILL_FIRE_request_get,
       WILL_FIRE_response_put;

  // declarations used by system tasks
  // synopsys translate_off
  reg [63 : 0] v__h2378;
  // synopsys translate_on

  // remaining internal signals
  reg [15 : 0] CASE_insn71_BITS_15_TO_13_0b0_st0_0b1_dstackD_ETC__q4,
	       y_avValue_fst__h1448;
  reg [14 : 0] IF_IF_pc_EQ_0_THEN_0x6000_ELSE_ram_a_read_BITS_ETC___d75;
  reg [4 : 0] CASE_insn71_BITS_15_TO_13_0b0_dsp_0b1_dsp584_0_ETC__q5,
	      CASE_insn71_BITS_15_TO_13_0b10_rsp86_0b11_rsp2_ETC__q6;
  wire [15 : 0] IF_IF_pc_EQ_0_THEN_0x6000_ELSE_ram_a_read_BITS_ETC___d122,
		_st0__h1467,
		insn__h771,
		v__h1039,
		v__h1079,
		x__h996,
		y_avValue_fst__h1433;
  wire [14 : 0] _pc__h1471,
		_theResult___snd_snd__h1586,
		x__h1018,
		y_avValue_snd_snd_snd_fst__h1544,
		y_avValue_snd_snd_snd_fst__h1546;
  wire [12 : 0] insn71_BITS_12_TO_0__q3, x__h1558, x__h1591, x__h1619;
  wire [4 : 0] _dsp__h1141, _dsp__h1584, _dsp__h934, _rsp__h1278, _rsp__h986;
  wire [1 : 0] insn71_BITS_1_TO_0__q1, insn71_BITS_3_TO_2__q2;
  wire st0_7_ULE_15___d101;

  // actionvalue method request_get
  assign request_get = io_req$D_OUT ;
  assign RDY_request_get = io_req$EMPTY_N ;
  assign CAN_FIRE_request_get = io_req$EMPTY_N ;
  assign WILL_FIRE_request_get = EN_request_get ;

  // action method response_put
  assign RDY_response_put = io_rsp$FULL_N ;
  assign CAN_FIRE_response_put = io_rsp$FULL_N ;
  assign WILL_FIRE_response_put = EN_response_put ;

  // submodule dstack
  RegFile #(.addr_width(32'd5),
	    .data_width(32'd16),
	    .lo(5'h0),
	    .hi(5'd31)) dstack(.CLK(CLK),
			       .ADDR_1(dstack$ADDR_1),
			       .ADDR_2(dstack$ADDR_2),
			       .ADDR_3(dstack$ADDR_3),
			       .ADDR_4(dstack$ADDR_4),
			       .ADDR_5(dstack$ADDR_5),
			       .ADDR_IN(dstack$ADDR_IN),
			       .D_IN(dstack$D_IN),
			       .WE(dstack$WE),
			       .D_OUT_1(dstack$D_OUT_1),
			       .D_OUT_2(),
			       .D_OUT_3(),
			       .D_OUT_4(),
			       .D_OUT_5());

  // submodule io_req
  FIFO2 #(.width(32'd35), .guarded(1'd1)) io_req(.RST(RST_N),
						 .CLK(CLK),
						 .D_IN(io_req$D_IN),
						 .ENQ(io_req$ENQ),
						 .DEQ(io_req$DEQ),
						 .CLR(io_req$CLR),
						 .D_OUT(io_req$D_OUT),
						 .FULL_N(io_req$FULL_N),
						 .EMPTY_N(io_req$EMPTY_N));

  // submodule io_rsp
  FIFO2 #(.width(32'd16), .guarded(1'd0)) io_rsp(.RST(RST_N),
						 .CLK(CLK),
						 .D_IN(io_rsp$D_IN),
						 .ENQ(io_rsp$ENQ),
						 .DEQ(io_rsp$DEQ),
						 .CLR(io_rsp$CLR),
						 .D_OUT(io_rsp$D_OUT),
						 .FULL_N(io_rsp$FULL_N),
						 .EMPTY_N(io_rsp$EMPTY_N));

  // submodule ram
  BRAM2Load #(.FILENAME("j1.hex"),
	      .PIPELINED(1'd0),
	      .ADDR_WIDTH(32'd14),
	      .DATA_WIDTH(32'd16),
	      .MEMSIZE(15'd16384),
	      .BINARY(1'd0)) ram(.CLKA(CLK),
				 .CLKB(CLK),
				 .ADDRA(ram$ADDRA),
				 .ADDRB(ram$ADDRB),
				 .DIA(ram$DIA),
				 .DIB(ram$DIB),
				 .WEA(ram$WEA),
				 .WEB(ram$WEB),
				 .ENA(ram$ENA),
				 .ENB(ram$ENB),
				 .DOA(ram$DOA),
				 .DOB(ram$DOB));

  // submodule rstack
  RegFile #(.addr_width(32'd5),
	    .data_width(32'd16),
	    .lo(5'h0),
	    .hi(5'd31)) rstack(.CLK(CLK),
			       .ADDR_1(rstack$ADDR_1),
			       .ADDR_2(rstack$ADDR_2),
			       .ADDR_3(rstack$ADDR_3),
			       .ADDR_4(rstack$ADDR_4),
			       .ADDR_5(rstack$ADDR_5),
			       .ADDR_IN(rstack$ADDR_IN),
			       .D_IN(rstack$D_IN),
			       .WE(rstack$WE),
			       .D_OUT_1(rstack$D_OUT_1),
			       .D_OUT_2(),
			       .D_OUT_3(),
			       .D_OUT_4(),
			       .D_OUT_5());

  // rule RL_run
  assign CAN_FIRE_RL_run = io_req$FULL_N ;
  assign WILL_FIRE_RL_run = io_req$FULL_N ;

  // register dsp
  assign dsp$D_IN =
	     (insn__h771[15:13] != 3'b0 && insn__h771[15:13] != 3'b001 &&
	      insn__h771[15:13] != 3'b010 &&
	      insn__h771[15:13] != 3'b011) ?
	       _dsp__h934 :
	       CASE_insn71_BITS_15_TO_13_0b0_dsp_0b1_dsp584_0_ETC__q5 ;
  assign dsp$EN = io_req$FULL_N ;

  // register pc
  assign pc$D_IN = _pc__h1471 ;
  assign pc$EN = io_req$FULL_N ;

  // register rsp
  assign rsp$D_IN =
	     (insn__h771[15:13] != 3'b010 && insn__h771[15:13] != 3'b011) ?
	       rsp :
	       CASE_insn71_BITS_15_TO_13_0b10_rsp86_0b11_rsp2_ETC__q6 ;
  assign rsp$EN = io_req$FULL_N ;

  // register st0
  assign st0$D_IN = _st0__h1467 ;
  assign st0$EN = io_req$FULL_N ;

  // submodule dstack
  assign dstack$ADDR_1 = dsp ;
  assign dstack$ADDR_2 = 5'h0 ;
  assign dstack$ADDR_3 = 5'h0 ;
  assign dstack$ADDR_4 = 5'h0 ;
  assign dstack$ADDR_5 = 5'h0 ;
  assign dstack$ADDR_IN =
	     (insn__h771[15:13] != 3'b0 && insn__h771[15:13] != 3'b001 &&
	      insn__h771[15:13] != 3'b010 &&
	      insn__h771[15:13] != 3'b011) ?
	       _dsp__h934 :
	       _dsp__h1141 ;
  assign dstack$D_IN = st0 ;
  assign dstack$WE =
	     io_req$FULL_N &&
	     (insn__h771[15:13] != 3'b0 && insn__h771[15:13] != 3'b001 &&
	      insn__h771[15:13] != 3'b010 &&
	      insn__h771[15:13] != 3'b011 ||
	      insn__h771[15:13] == 3'b011 && insn__h771[7]) ;

  // submodule io_req
  assign io_req$D_IN =
	     { insn__h771[15:13] == 3'b011 && insn__h771[5],
	       2'd3,
	       _st0__h1467,
	       dstack$D_OUT_1 } ;
  assign io_req$ENQ =
	     io_req$FULL_N && _st0__h1467[15:14] != 2'd0 &&
	     insn__h771[15:13] == 3'b011 &&
	     (insn__h771[11:8] == 4'd12 || insn__h771[5]) ;
  assign io_req$DEQ = EN_request_get ;
  assign io_req$CLR = 1'b0 ;

  // submodule io_rsp
  assign io_rsp$D_IN = response_put ;
  assign io_rsp$ENQ = EN_response_put ;
  assign io_rsp$DEQ =
	     io_req$FULL_N && insn__h771[15:13] == 3'b011 &&
	     st0[15:14] != 2'd0 &&
	     io_rsp$EMPTY_N ;
  assign io_rsp$CLR = 1'b0 ;

  // submodule ram
  assign ram$ADDRA = _pc__h1471[14:1] ;
  assign ram$ADDRB = _st0__h1467[14:1] ;
  assign ram$DIA = 16'd0 ;
  assign ram$DIB = dstack$D_OUT_1 ;
  assign ram$WEA = 1'd0 ;
  assign ram$WEB = insn__h771[15:13] == 3'b011 && insn__h771[5] ;
  assign ram$ENA = io_req$FULL_N ;
  assign ram$ENB = io_req$FULL_N && _st0__h1467[15:14] == 2'd0 ;

  // submodule rstack
  assign rstack$ADDR_1 = rsp ;
  assign rstack$ADDR_2 = 5'h0 ;
  assign rstack$ADDR_3 = 5'h0 ;
  assign rstack$ADDR_4 = 5'h0 ;
  assign rstack$ADDR_5 = 5'h0 ;
  assign rstack$ADDR_IN =
	     (insn__h771[15:13] == 3'b010) ? _rsp__h986 : _rsp__h1278 ;
  assign rstack$D_IN = (insn__h771[15:13] == 3'b010) ? x__h996 : st0 ;
  assign rstack$WE =
	     io_req$FULL_N &&
	     (insn__h771[15:13] == 3'b010 ||
	      insn__h771[15:13] == 3'b011 && insn__h771[6]) ;

  // remaining internal signals
  assign IF_IF_pc_EQ_0_THEN_0x6000_ELSE_ram_a_read_BITS_ETC___d122 =
	     (dstack$D_OUT_1 < st0) ? 16'd65535 : 16'd0 ;
  assign _dsp__h1141 =
	     dsp +
	     { {3{insn71_BITS_1_TO_0__q1[1]}}, insn71_BITS_1_TO_0__q1 } ;
  assign _dsp__h1584 = dsp - 5'd1 ;
  assign _dsp__h934 = dsp + 5'd1 ;
  assign _pc__h1471 =
	     (insn__h771[15:13] != 3'b0 && insn__h771[15:13] != 3'b001 &&
	      insn__h771[15:13] != 3'b010 &&
	      insn__h771[15:13] != 3'b011) ?
	       x__h1018 :
	       IF_IF_pc_EQ_0_THEN_0x6000_ELSE_ram_a_read_BITS_ETC___d75 ;
  assign _rsp__h1278 =
	     rsp +
	     { {3{insn71_BITS_3_TO_2__q2[1]}}, insn71_BITS_3_TO_2__q2 } ;
  assign _rsp__h986 = rsp + 5'd1 ;
  assign _st0__h1467 =
	     (insn__h771[15:13] != 3'b0 && insn__h771[15:13] != 3'b001 &&
	      insn__h771[15:13] != 3'b010 &&
	      insn__h771[15:13] != 3'b011) ?
	       y_avValue_fst__h1433 :
	       CASE_insn71_BITS_15_TO_13_0b0_st0_0b1_dstackD_ETC__q4 ;
  assign _theResult___snd_snd__h1586 =
	     (st0 == 16'd0) ? { 2'd0, x__h1591 } : x__h1018 ;
  assign insn71_BITS_12_TO_0__q3 = insn__h771[12:0] ;
  assign insn71_BITS_1_TO_0__q1 = insn__h771[1:0] ;
  assign insn71_BITS_3_TO_2__q2 = insn__h771[3:2] ;
  assign insn__h771 = (pc == 15'd0) ? 16'h6000 : ram$DOA ;
  assign st0_7_ULE_15___d101 = st0 <= 16'd15 ;
  assign v__h1039 = (st0[15:14] == 2'd0) ? ram$DOB : v__h1079 ;
  assign v__h1079 = io_rsp$EMPTY_N ? io_rsp$D_OUT : st0 ;
  assign x__h1018 = pc + 15'd2 ;
  assign x__h1558 = { insn71_BITS_12_TO_0__q3[11:0], 1'd0 } ;
  assign x__h1591 = x__h1558 ;
  assign x__h1619 = x__h1558 ;
  assign x__h996 = { 1'd0, x__h1018 } ;
  assign y_avValue_fst__h1433 = { 1'd0, insn__h771[14:0] } ;
  assign y_avValue_snd_snd_snd_fst__h1544 = { 2'd0, x__h1619 } ;
  assign y_avValue_snd_snd_snd_fst__h1546 =
	     insn__h771[12] ? rstack$D_OUT_1[14:0] : x__h1018 ;
  always@(insn__h771 or
	  IF_IF_pc_EQ_0_THEN_0x6000_ELSE_ram_a_read_BITS_ETC___d122 or
	  st0 or
	  dstack$D_OUT_1 or
	  st0_7_ULE_15___d101 or rstack$D_OUT_1 or v__h1039 or rsp or dsp)
  begin
    case (insn__h771[11:8])
      4'd0: y_avValue_fst__h1448 = st0;
      4'd1: y_avValue_fst__h1448 = dstack$D_OUT_1;
      4'd2: y_avValue_fst__h1448 = st0 + dstack$D_OUT_1;
      4'd3: y_avValue_fst__h1448 = st0 & dstack$D_OUT_1;
      4'd4: y_avValue_fst__h1448 = st0 | dstack$D_OUT_1;
      4'd5: y_avValue_fst__h1448 = st0 ^ dstack$D_OUT_1;
      4'd6: y_avValue_fst__h1448 = ~st0;
      4'd7:
	  y_avValue_fst__h1448 = (dstack$D_OUT_1 == st0) ? 16'd65535 : 16'd0;
      4'd8:
	  y_avValue_fst__h1448 =
	      ((dstack$D_OUT_1 ^ 16'h8000) < (st0 ^ 16'h8000)) ?
		16'd65535 :
		16'd0;
      4'd9:
	  y_avValue_fst__h1448 =
	      st0_7_ULE_15___d101 ? dstack$D_OUT_1 >> st0[3:0] : 16'd0;
      4'd10: y_avValue_fst__h1448 = st0 - 16'd1;
      4'd11: y_avValue_fst__h1448 = rstack$D_OUT_1;
      4'd12: y_avValue_fst__h1448 = v__h1039;
      4'd13:
	  y_avValue_fst__h1448 =
	      st0_7_ULE_15___d101 ? dstack$D_OUT_1 << st0[3:0] : 16'd0;
      4'd14: y_avValue_fst__h1448 = { 3'b0, rsp, 3'b0, dsp };
      4'd15:
	  y_avValue_fst__h1448 =
	      IF_IF_pc_EQ_0_THEN_0x6000_ELSE_ram_a_read_BITS_ETC___d122;
    endcase
  end
  always@(insn__h771 or st0 or dstack$D_OUT_1 or y_avValue_fst__h1448)
  begin
    case (insn__h771[15:13])
      3'b0, 3'b010:
	  CASE_insn71_BITS_15_TO_13_0b0_st0_0b1_dstackD_ETC__q4 = st0;
      3'b001:
	  CASE_insn71_BITS_15_TO_13_0b0_st0_0b1_dstackD_ETC__q4 =
	      dstack$D_OUT_1;
      3'b011:
	  CASE_insn71_BITS_15_TO_13_0b0_st0_0b1_dstackD_ETC__q4 =
	      y_avValue_fst__h1448;
      default: CASE_insn71_BITS_15_TO_13_0b0_st0_0b1_dstackD_ETC__q4 = st0;
    endcase
  end
  always@(insn__h771 or
	  pc or
	  x__h1558 or
	  _theResult___snd_snd__h1586 or
	  y_avValue_snd_snd_snd_fst__h1544 or
	  y_avValue_snd_snd_snd_fst__h1546)
  begin
    case (insn__h771[15:13])
      3'b0:
	  IF_IF_pc_EQ_0_THEN_0x6000_ELSE_ram_a_read_BITS_ETC___d75 =
	      { 2'd0, x__h1558 };
      3'b001:
	  IF_IF_pc_EQ_0_THEN_0x6000_ELSE_ram_a_read_BITS_ETC___d75 =
	      _theResult___snd_snd__h1586;
      3'b010:
	  IF_IF_pc_EQ_0_THEN_0x6000_ELSE_ram_a_read_BITS_ETC___d75 =
	      y_avValue_snd_snd_snd_fst__h1544;
      3'b011:
	  IF_IF_pc_EQ_0_THEN_0x6000_ELSE_ram_a_read_BITS_ETC___d75 =
	      y_avValue_snd_snd_snd_fst__h1546;
      default: IF_IF_pc_EQ_0_THEN_0x6000_ELSE_ram_a_read_BITS_ETC___d75 = pc;
    endcase
  end
  always@(insn__h771 or dsp or _dsp__h1584 or _dsp__h1141)
  begin
    case (insn__h771[15:13])
      3'b0, 3'b010:
	  CASE_insn71_BITS_15_TO_13_0b0_dsp_0b1_dsp584_0_ETC__q5 = dsp;
      3'b001:
	  CASE_insn71_BITS_15_TO_13_0b0_dsp_0b1_dsp584_0_ETC__q5 =
	      _dsp__h1584;
      3'b011:
	  CASE_insn71_BITS_15_TO_13_0b0_dsp_0b1_dsp584_0_ETC__q5 =
	      _dsp__h1141;
      default: CASE_insn71_BITS_15_TO_13_0b0_dsp_0b1_dsp584_0_ETC__q5 = dsp;
    endcase
  end
  always@(insn__h771 or rsp or _rsp__h986 or _rsp__h1278)
  begin
    case (insn__h771[15:13])
      3'b010:
	  CASE_insn71_BITS_15_TO_13_0b10_rsp86_0b11_rsp2_ETC__q6 = _rsp__h986;
      3'b011:
	  CASE_insn71_BITS_15_TO_13_0b10_rsp86_0b11_rsp2_ETC__q6 =
	      _rsp__h1278;
      default: CASE_insn71_BITS_15_TO_13_0b10_rsp86_0b11_rsp2_ETC__q6 = rsp;
    endcase
  end

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        dsp <= `BSV_ASSIGNMENT_DELAY 5'd0;
	pc <= `BSV_ASSIGNMENT_DELAY 15'd0;
	rsp <= `BSV_ASSIGNMENT_DELAY 5'd0;
      end
    else
      begin
        if (dsp$EN) dsp <= `BSV_ASSIGNMENT_DELAY dsp$D_IN;
	if (pc$EN) pc <= `BSV_ASSIGNMENT_DELAY pc$D_IN;
	if (rsp$EN) rsp <= `BSV_ASSIGNMENT_DELAY rsp$D_IN;
      end
    if (st0$EN) st0 <= `BSV_ASSIGNMENT_DELAY st0$D_IN;
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    dsp = 5'h0A;
    pc = 15'h2AAA;
    rsp = 5'h0A;
    st0 = 16'hAAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      if (io_req$FULL_N)
	begin
	  v__h2378 = $time;
	  #0;
	end
    if (RST_N != `BSV_RESET_VALUE)
      if (io_req$FULL_N)
	$display("%t: pc=%h insn=%h dsp=%h st0=%h st1=%h rsp=%h rst0=%h",
		 v__h2378,
		 pc,
		 insn__h771,
		 dsp,
		 st0,
		 dstack$D_OUT_1,
		 rsp,
		 rstack$D_OUT_1);
  end
  // synopsys translate_on
endmodule  // mkJ1

