//
// Generated by Bluespec Compiler, version 2021.07 (build 4cac6eb)
//
// On Sat Oct  2 11:20:03 CEST 2021
//
//
// Ports:
// Name                         I/O  size props
// request_get                    O    35 reg
// RDY_request_get                O     1 reg
// RDY_response_put               O     1 reg
// CLK                            I     1 clock
// RST_N                          I     1 reset
// response_put                   I    16 reg
// EN_response_put                I     1
// EN_request_get                 I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkJ1(CLK,
	    RST_N,

	    EN_request_get,
	    request_get,
	    RDY_request_get,

	    response_put,
	    EN_response_put,
	    RDY_response_put);
  input  CLK;
  input  RST_N;

  // actionvalue method request_get
  input  EN_request_get;
  output [34 : 0] request_get;
  output RDY_request_get;

  // action method response_put
  input  [15 : 0] response_put;
  input  EN_response_put;
  output RDY_response_put;

  // signals for module outputs
  wire [34 : 0] request_get;
  wire RDY_request_get, RDY_response_put;

  // register dsp
  reg [4 : 0] dsp;
  wire [4 : 0] dsp$D_IN;
  wire dsp$EN;

  // register pc
  reg [14 : 0] pc;
  wire [14 : 0] pc$D_IN;
  wire pc$EN;

  // register rsp
  reg [4 : 0] rsp;
  wire [4 : 0] rsp$D_IN;
  wire rsp$EN;

  // register st0
  reg [15 : 0] st0;
  wire [15 : 0] st0$D_IN;
  wire st0$EN;

  // ports of submodule dstack
  wire [15 : 0] dstack$D_IN, dstack$D_OUT_1;
  wire [4 : 0] dstack$ADDR_1,
	       dstack$ADDR_2,
	       dstack$ADDR_3,
	       dstack$ADDR_4,
	       dstack$ADDR_5,
	       dstack$ADDR_IN;
  wire dstack$WE;

  // ports of submodule io_req
  wire [34 : 0] io_req$D_IN, io_req$D_OUT;
  wire io_req$CLR, io_req$DEQ, io_req$EMPTY_N, io_req$ENQ;

  // ports of submodule io_rsp
  wire [15 : 0] io_rsp$D_IN;
  wire io_rsp$CLR, io_rsp$DEQ, io_rsp$ENQ, io_rsp$FULL_N;

  // ports of submodule ram
  wire [15 : 0] ram$DIA, ram$DIB, ram$DOA, ram$DOB;
  wire [13 : 0] ram$ADDRA, ram$ADDRB;
  wire ram$ENA, ram$ENB, ram$WEA, ram$WEB;

  // ports of submodule rstack
  wire [15 : 0] rstack$D_IN, rstack$D_OUT_1;
  wire [4 : 0] rstack$ADDR_1,
	       rstack$ADDR_2,
	       rstack$ADDR_3,
	       rstack$ADDR_4,
	       rstack$ADDR_5,
	       rstack$ADDR_IN;
  wire rstack$WE;

  // declarations used by system tasks
  // synopsys translate_off
  reg [63 : 0] v__h2905;
  // synopsys translate_on

  // remaining internal signals
  reg [15 : 0] CASE_insn67_BITS_14_TO_13_0b0_st0_0b1_dstackD_ETC__q3,
	       y_avValue_fst__h1709;
  reg [14 : 0] IF_IF_pc_EQ_0_THEN_0x6000_ELSE_ram_a_read_BITS_ETC___d53;
  reg [4 : 0] CASE_insn67_BITS_14_TO_13_0b0_dsp_0b1_dsp846_0_ETC__q4,
	      CASE_insn67_BITS_14_TO_13_0b10_rsp017_0b11_rsp_ETC__q5;
  wire [15 : 0] IF_IF_IF_pc_EQ_0_THEN_0x6000_ELSE_ram_a_read_B_ETC___d101,
		_st0__h1728,
		insn__h767,
		x__h1027,
		y_avValue_fst__h1695;
  wire [14 : 0] _pc__h1732,
		_theResult___snd_snd__h1848,
		x__h1049,
		y_avValue_snd_snd_snd_fst__h1805,
		y_avValue_snd_snd_snd_fst__h1806;
  wire [13 : 0] x__h1884;
  wire [4 : 0] _dsp__h1066, _dsp__h1846, _dsp__h966, _rsp__h1017, _rsp__h1370;
  wire [1 : 0] insn67_BITS_1_TO_0__q1, insn67_BITS_3_TO_2__q2;
  wire st0_8_ULE_15___d80;

  // actionvalue method request_get
  assign request_get = io_req$D_OUT ;
  assign RDY_request_get = io_req$EMPTY_N ;

  // action method response_put
  assign RDY_response_put = io_rsp$FULL_N ;

  // submodule dstack
  RegFile #(.addr_width(32'd5),
	    .data_width(32'd16),
	    .lo(5'h0),
	    .hi(5'd31)) dstack(.CLK(CLK),
			       .ADDR_1(dstack$ADDR_1),
			       .ADDR_2(dstack$ADDR_2),
			       .ADDR_3(dstack$ADDR_3),
			       .ADDR_4(dstack$ADDR_4),
			       .ADDR_5(dstack$ADDR_5),
			       .ADDR_IN(dstack$ADDR_IN),
			       .D_IN(dstack$D_IN),
			       .WE(dstack$WE),
			       .D_OUT_1(dstack$D_OUT_1),
			       .D_OUT_2(),
			       .D_OUT_3(),
			       .D_OUT_4(),
			       .D_OUT_5());

  // submodule io_req
  FIFO2 #(.width(32'd35), .guarded(1'd1)) io_req(.RST(RST_N),
						 .CLK(CLK),
						 .D_IN(io_req$D_IN),
						 .ENQ(io_req$ENQ),
						 .DEQ(io_req$DEQ),
						 .CLR(io_req$CLR),
						 .D_OUT(io_req$D_OUT),
						 .FULL_N(),
						 .EMPTY_N(io_req$EMPTY_N));

  // submodule io_rsp
  FIFO2 #(.width(32'd16), .guarded(1'd1)) io_rsp(.RST(RST_N),
						 .CLK(CLK),
						 .D_IN(io_rsp$D_IN),
						 .ENQ(io_rsp$ENQ),
						 .DEQ(io_rsp$DEQ),
						 .CLR(io_rsp$CLR),
						 .D_OUT(),
						 .FULL_N(io_rsp$FULL_N),
						 .EMPTY_N());

  // submodule ram
  BRAM2Load #(.FILENAME("j1.hex"),
	      .PIPELINED(1'd0),
	      .ADDR_WIDTH(32'd14),
	      .DATA_WIDTH(32'd16),
	      .MEMSIZE(15'd16384),
	      .BINARY(1'd0)) ram(.CLKA(CLK),
				 .CLKB(CLK),
				 .ADDRA(ram$ADDRA),
				 .ADDRB(ram$ADDRB),
				 .DIA(ram$DIA),
				 .DIB(ram$DIB),
				 .WEA(ram$WEA),
				 .WEB(ram$WEB),
				 .ENA(ram$ENA),
				 .ENB(ram$ENB),
				 .DOA(ram$DOA),
				 .DOB(ram$DOB));

  // submodule rstack
  RegFile #(.addr_width(32'd5),
	    .data_width(32'd16),
	    .lo(5'h0),
	    .hi(5'd31)) rstack(.CLK(CLK),
			       .ADDR_1(rstack$ADDR_1),
			       .ADDR_2(rstack$ADDR_2),
			       .ADDR_3(rstack$ADDR_3),
			       .ADDR_4(rstack$ADDR_4),
			       .ADDR_5(rstack$ADDR_5),
			       .ADDR_IN(rstack$ADDR_IN),
			       .D_IN(rstack$D_IN),
			       .WE(rstack$WE),
			       .D_OUT_1(rstack$D_OUT_1),
			       .D_OUT_2(),
			       .D_OUT_3(),
			       .D_OUT_4(),
			       .D_OUT_5());

  // register dsp
  assign dsp$D_IN =
	     insn__h767[15] ?
	       _dsp__h966 :
	       CASE_insn67_BITS_14_TO_13_0b0_dsp_0b1_dsp846_0_ETC__q4 ;
  assign dsp$EN = 1'd1 ;

  // register pc
  assign pc$D_IN = _pc__h1732 ;
  assign pc$EN = 1'd1 ;

  // register rsp
  assign rsp$D_IN =
	     (insn__h767[15] || insn__h767[14:13] == 2'b0 ||
	      insn__h767[14:13] == 2'b01) ?
	       rsp :
	       CASE_insn67_BITS_14_TO_13_0b10_rsp017_0b11_rsp_ETC__q5 ;
  assign rsp$EN = 1'd1 ;

  // register st0
  assign st0$D_IN = _st0__h1728 ;
  assign st0$EN = 1'd1 ;

  // submodule dstack
  assign dstack$ADDR_1 = dsp ;
  assign dstack$ADDR_2 = 5'h0 ;
  assign dstack$ADDR_3 = 5'h0 ;
  assign dstack$ADDR_4 = 5'h0 ;
  assign dstack$ADDR_5 = 5'h0 ;
  assign dstack$ADDR_IN = insn__h767[15] ? _dsp__h966 : _dsp__h1066 ;
  assign dstack$D_IN = st0 ;
  assign dstack$WE =
	     insn__h767[15] || insn__h767[14:13] == 2'b11 && insn__h767[7] ;

  // submodule io_req
  assign io_req$D_IN = 35'h0 ;
  assign io_req$ENQ = 1'b0 ;
  assign io_req$DEQ = EN_request_get ;
  assign io_req$CLR = 1'b0 ;

  // submodule io_rsp
  assign io_rsp$D_IN = response_put ;
  assign io_rsp$ENQ = EN_response_put ;
  assign io_rsp$DEQ = 1'b0 ;
  assign io_rsp$CLR = 1'b0 ;

  // submodule ram
  assign ram$ADDRA = _pc__h1732[14:1] ;
  assign ram$ADDRB = _st0__h1728[14:1] ;
  assign ram$DIA = 16'b1010101010101010 /* unspecified value */  ;
  assign ram$DIB = dstack$D_OUT_1 ;
  assign ram$WEA = 1'd0 ;
  assign ram$WEB =
	     !insn__h767[15] && insn__h767[14:13] == 2'b11 && insn__h767[5] ;
  assign ram$ENA = 1'd1 ;
  assign ram$ENB = _st0__h1728[15:14] == 2'd0 ;

  // submodule rstack
  assign rstack$ADDR_1 = rsp ;
  assign rstack$ADDR_2 = 5'h0 ;
  assign rstack$ADDR_3 = 5'h0 ;
  assign rstack$ADDR_4 = 5'h0 ;
  assign rstack$ADDR_5 = 5'h0 ;
  assign rstack$ADDR_IN =
	     (insn__h767[14:13] == 2'b10) ? _rsp__h1017 : _rsp__h1370 ;
  assign rstack$D_IN = (insn__h767[14:13] == 2'b10) ? x__h1027 : st0 ;
  assign rstack$WE =
	     !insn__h767[15] &&
	     (insn__h767[14:13] == 2'b10 ||
	      insn__h767[14:13] == 2'b11 && insn__h767[6]) ;

  // remaining internal signals
  assign IF_IF_IF_pc_EQ_0_THEN_0x6000_ELSE_ram_a_read_B_ETC___d101 =
	     (dstack$D_OUT_1 < st0) ? 16'd65535 : 16'd0 ;
  assign _dsp__h1066 =
	     dsp +
	     { {3{insn67_BITS_1_TO_0__q1[1]}}, insn67_BITS_1_TO_0__q1 } ;
  assign _dsp__h1846 = dsp - 5'd1 ;
  assign _dsp__h966 = dsp + 5'd1 ;
  assign _pc__h1732 =
	     insn__h767[15] ?
	       x__h1049 :
	       IF_IF_pc_EQ_0_THEN_0x6000_ELSE_ram_a_read_BITS_ETC___d53 ;
  assign _rsp__h1017 = rsp + 5'd1 ;
  assign _rsp__h1370 =
	     rsp +
	     { {3{insn67_BITS_3_TO_2__q2[1]}}, insn67_BITS_3_TO_2__q2 } ;
  assign _st0__h1728 =
	     insn__h767[15] ?
	       y_avValue_fst__h1695 :
	       CASE_insn67_BITS_14_TO_13_0b0_st0_0b1_dstackD_ETC__q3 ;
  assign _theResult___snd_snd__h1848 =
	     (st0 == 16'd0) ? y_avValue_snd_snd_snd_fst__h1805 : x__h1049 ;
  assign insn67_BITS_1_TO_0__q1 = insn__h767[1:0] ;
  assign insn67_BITS_3_TO_2__q2 = insn__h767[3:2] ;
  assign insn__h767 = (pc == 15'd0) ? 16'h6000 : ram$DOA ;
  assign st0_8_ULE_15___d80 = st0 <= 16'd15 ;
  assign x__h1027 = { 1'd0, x__h1049 } ;
  assign x__h1049 = pc + 15'd2 ;
  assign x__h1884 = { insn__h767[12:0], 1'b0 } ;
  assign y_avValue_fst__h1695 = { 1'b0, insn__h767[14:0] } ;
  assign y_avValue_snd_snd_snd_fst__h1805 = { 1'd0, x__h1884 } ;
  assign y_avValue_snd_snd_snd_fst__h1806 =
	     insn__h767[12] ? rstack$D_OUT_1[14:0] : x__h1049 ;
  always@(insn__h767 or
	  IF_IF_IF_pc_EQ_0_THEN_0x6000_ELSE_ram_a_read_B_ETC___d101 or
	  st0 or
	  dstack$D_OUT_1 or
	  st0_8_ULE_15___d80 or rstack$D_OUT_1 or ram$DOB or rsp or dsp)
  begin
    case (insn__h767[11:8])
      4'd0: y_avValue_fst__h1709 = st0;
      4'd1: y_avValue_fst__h1709 = dstack$D_OUT_1;
      4'd2: y_avValue_fst__h1709 = st0 + dstack$D_OUT_1;
      4'd3: y_avValue_fst__h1709 = st0 & dstack$D_OUT_1;
      4'd4: y_avValue_fst__h1709 = st0 | dstack$D_OUT_1;
      4'd5: y_avValue_fst__h1709 = st0 ^ dstack$D_OUT_1;
      4'd6: y_avValue_fst__h1709 = ~st0;
      4'd7:
	  y_avValue_fst__h1709 = (dstack$D_OUT_1 == st0) ? 16'd65535 : 16'd0;
      4'd8:
	  y_avValue_fst__h1709 =
	      ((dstack$D_OUT_1 ^ 16'h8000) < (st0 ^ 16'h8000)) ?
		16'd65535 :
		16'd0;
      4'd9:
	  y_avValue_fst__h1709 =
	      st0_8_ULE_15___d80 ? dstack$D_OUT_1 >> st0[3:0] : 16'd0;
      4'd10: y_avValue_fst__h1709 = st0 - 16'd1;
      4'd11: y_avValue_fst__h1709 = rstack$D_OUT_1;
      4'd12: y_avValue_fst__h1709 = ram$DOB;
      4'd13:
	  y_avValue_fst__h1709 =
	      st0_8_ULE_15___d80 ? dstack$D_OUT_1 << st0[3:0] : 16'd0;
      4'd14: y_avValue_fst__h1709 = { 3'b0, rsp, 3'b0, dsp };
      4'd15:
	  y_avValue_fst__h1709 =
	      IF_IF_IF_pc_EQ_0_THEN_0x6000_ELSE_ram_a_read_B_ETC___d101;
    endcase
  end
  always@(insn__h767 or st0 or dstack$D_OUT_1 or y_avValue_fst__h1709)
  begin
    case (insn__h767[14:13])
      2'b0, 2'b10:
	  CASE_insn67_BITS_14_TO_13_0b0_st0_0b1_dstackD_ETC__q3 = st0;
      2'b01:
	  CASE_insn67_BITS_14_TO_13_0b0_st0_0b1_dstackD_ETC__q3 =
	      dstack$D_OUT_1;
      2'b11:
	  CASE_insn67_BITS_14_TO_13_0b0_st0_0b1_dstackD_ETC__q3 =
	      y_avValue_fst__h1709;
    endcase
  end
  always@(insn__h767 or
	  pc or
	  y_avValue_snd_snd_snd_fst__h1805 or
	  _theResult___snd_snd__h1848 or y_avValue_snd_snd_snd_fst__h1806)
  begin
    case (insn__h767[14:13])
      2'b0, 2'b10:
	  IF_IF_pc_EQ_0_THEN_0x6000_ELSE_ram_a_read_BITS_ETC___d53 =
	      y_avValue_snd_snd_snd_fst__h1805;
      2'b01:
	  IF_IF_pc_EQ_0_THEN_0x6000_ELSE_ram_a_read_BITS_ETC___d53 =
	      _theResult___snd_snd__h1848;
      2'b11:
	  IF_IF_pc_EQ_0_THEN_0x6000_ELSE_ram_a_read_BITS_ETC___d53 =
	      y_avValue_snd_snd_snd_fst__h1806;
    endcase
  end
  always@(insn__h767 or dsp or _dsp__h1846 or _dsp__h1066)
  begin
    case (insn__h767[14:13])
      2'b0, 2'b10:
	  CASE_insn67_BITS_14_TO_13_0b0_dsp_0b1_dsp846_0_ETC__q4 = dsp;
      2'b01:
	  CASE_insn67_BITS_14_TO_13_0b0_dsp_0b1_dsp846_0_ETC__q4 =
	      _dsp__h1846;
      2'b11:
	  CASE_insn67_BITS_14_TO_13_0b0_dsp_0b1_dsp846_0_ETC__q4 =
	      _dsp__h1066;
    endcase
  end
  always@(insn__h767 or rsp or _rsp__h1017 or _rsp__h1370)
  begin
    case (insn__h767[14:13])
      2'b10:
	  CASE_insn67_BITS_14_TO_13_0b10_rsp017_0b11_rsp_ETC__q5 =
	      _rsp__h1017;
      2'b11:
	  CASE_insn67_BITS_14_TO_13_0b10_rsp017_0b11_rsp_ETC__q5 =
	      _rsp__h1370;
      default: CASE_insn67_BITS_14_TO_13_0b10_rsp017_0b11_rsp_ETC__q5 = rsp;
    endcase
  end

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        dsp <= `BSV_ASSIGNMENT_DELAY 5'd0;
	pc <= `BSV_ASSIGNMENT_DELAY 15'd0;
	rsp <= `BSV_ASSIGNMENT_DELAY 5'd0;
      end
    else
      begin
        if (dsp$EN) dsp <= `BSV_ASSIGNMENT_DELAY dsp$D_IN;
	if (pc$EN) pc <= `BSV_ASSIGNMENT_DELAY pc$D_IN;
	if (rsp$EN) rsp <= `BSV_ASSIGNMENT_DELAY rsp$D_IN;
      end
    if (st0$EN) st0 <= `BSV_ASSIGNMENT_DELAY st0$D_IN;
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    dsp = 5'h0A;
    pc = 15'h2AAA;
    rsp = 5'h0A;
    st0 = 16'hAAAA;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on

  // handling of system tasks

  // synopsys translate_off
  always@(negedge CLK)
  begin
    #0;
    if (RST_N != `BSV_RESET_VALUE)
      begin
        v__h2905 = $time;
	#0;
      end
    if (RST_N != `BSV_RESET_VALUE)
      $display("%t: pc=%h insn=%h dsp=%h st0=%h st1=%h rsp=%h rst0=%h",
	       v__h2905,
	       pc,
	       insn__h767,
	       dsp,
	       st0,
	       dstack$D_OUT_1,
	       rsp,
	       rstack$D_OUT_1);
  end
  // synopsys translate_on
endmodule  // mkJ1

