//
// Generated by Bluespec Compiler, version 2021.07 (build 4cac6eb)
//
// On Sun Oct  3 10:39:31 CEST 2021
//
//
// Ports:
// Name                         I/O  size props
// CLK                            I     1 clock
// RST_N                          I     1 reset
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkTb(CLK,
	    RST_N);
  input  CLK;
  input  RST_N;

  // ports of submodule dut
  wire [34 : 0] dut$request_get;
  wire [15 : 0] dut$response_put;
  wire dut$EN_request_get,
       dut$EN_response_put,
       dut$RDY_request_get,
       dut$RDY_response_put;

  // ports of submodule io
  wire [34 : 0] io$request_put;
  wire [15 : 0] io$response_get;
  wire io$EN_request_put,
       io$EN_response_get,
       io$RDY_request_put,
       io$RDY_response_get;

  // submodule dut
  mkJ1 dut(.CLK(CLK),
	   .RST_N(RST_N),
	   .response_put(dut$response_put),
	   .EN_request_get(dut$EN_request_get),
	   .EN_response_put(dut$EN_response_put),
	   .request_get(dut$request_get),
	   .RDY_request_get(dut$RDY_request_get),
	   .RDY_response_put(dut$RDY_response_put));

  // submodule io
  mkDummyIO io(.CLK(CLK),
	       .RST_N(RST_N),
	       .request_put(io$request_put),
	       .EN_request_put(io$EN_request_put),
	       .EN_response_get(io$EN_response_get),
	       .RDY_request_put(io$RDY_request_put),
	       .response_get(io$response_get),
	       .RDY_response_get(io$RDY_response_get));

  // submodule dut
  assign dut$response_put = io$response_get ;
  assign dut$EN_request_get = dut$RDY_request_get && io$RDY_request_put ;
  assign dut$EN_response_put = dut$RDY_response_put && io$RDY_response_get ;

  // submodule io
  assign io$request_put = dut$request_get ;
  assign io$EN_request_put = dut$RDY_request_get && io$RDY_request_put ;
  assign io$EN_response_get = dut$RDY_response_put && io$RDY_response_get ;
endmodule  // mkTb

